 services:

    postgres:
      image: bitnami/postgresql:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRESQL_USER: admin
        POSTGRESQL_PASSWORD: admin
        POSTGRESQL_DATABASE: casafacil

#Acessar DB psql -h localhost -U myuser -d mydatabase
#docker compose exec postgres psql -U tasks -d tasks